import type { Metadata } from "next";
import { Exo } from "next/font/google";
import "./globals.css";
import Navbar from "./-commponent/Navbar/Navbar";
import Footer from "./-commponent/Footer/Footer";
import TopNav from "./-commponent/TopNav/TopNav";

const exo = Exo({
  variable: "--font-exo",
  weight: ["100", "400", "700"],
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${exo.className} ${exo.variable} h-full antialiased`}
    >
      <body className="">
        <TopNav/>
         <Navbar/>

        {children}

         <Footer/>
        </body>
    </html>
  );
}
